---
title:  "[Node]Promise, async, await, 비동기" 

categories:
  - javascript
  
date: 2022-02-24 
toc: true
toc_sticky: true

---

## ☑️ 비동기

* 동시에 여러 작업을 수행할 수 있다.
* 대표적인 예 setTimeout


## ☑️ Promise?
<br/>

 ``` promise ```는 비동기 작업의 단위입니다.  
 프로미스를 통해 어떻게 비동기 작업들을 쉽게 관리할 수 있을까요
 

> 사용법
```yaml
const promise = new Promise((resolve, reject) => {
  // 비동기 작업
}) 
``` 
new Promise로 Promise 객체를 새롭게 만들어준 후 resolve와 reject를 인수로 받습니다.  
resolve는 "작업 성공"이란 의미이며 reject는 "작업 실패"란 의미 입니다.

<br/>

> then, catch
* then 메소드는 해당 promise가 성공했을 때의 동작을 지정합니다.
* catch 메소드는 해당 promise가 실패했을 때의 동작을 지정합니다.
* 예제
```yaml
const promise = new Promise((resolve, reject) => {
  resolve(); // reject()를 넣어주면 "실패" 출력
});

promise
  .then(() => {
    console.log("성공!"); 
  })
  .catch(() => {
    console.log("실패!");
  });
```

<br/>

## ☑️ async, await

<br/>

> async
* 함수를 선언할 때 async 키워드를 붙입니다.
* async 함수는 비동기 작업 그 자체를 뜻한다.
* promise -> async로 변환 예제
```yaml
// promise(기존)
// function changeAsync(age) {
//  return new Promise((resolve, reject) => {
//    if (age > 20) resolve(`${age}`);    
//   else reject(new Error("실패"));
//  });
// }

// async(변경)
async function changeAsync(age) {
  if (age > 20) return `${age}`;
  else throw new Error(`${age}는 20보다 큽니다.`);
}
```

<br/>

> await
* promise가 끝날때까지 기다린다.
* async 함수에서만 사용할 수 있다.
* 문법: ```await [[promise 객체]]``` 
* await 예제
```yaml
function setTimeoutPromise(ms) {
  return new Promise((resolve, reject) => {
    setTimeout(() => resolve(), ms);
  });
}

async function changeAsync(age) {
  if (age > 20) return `${age} success`;
  else throw new Error(`${age}는 20보다 큽니다.`);
}

async function changeAsyncJobs() {
  await setTimeoutPromise(1000);
  const promise1 = changeAsync(25);
  try {
    const value = await promise1;
    console.log(value);
  } catch (e) {
    console.error(e);
  }
  const promise2 = changeAsync(15);
  try {
    const value = await promise2;
    console.log(value);
  } catch (e) {
    console.error(e);
  }
}

changeAsyncJobs();
```
* await은 promise가 resolve한 값을 출력합니다.
* promise에서 reject가 발생한다면 예외가 발생합니다. (try catch)

<br/>


  
